### ISSUE TITLE
Decide on the headers

### ISSUE THREAD

**Issue by danielquinn** [HackBrexit/MinistersUnderTheInfluence#13]
After the discussion last night I think an easy(ish) first step for all of us is to work out the list of column headers and tags we're going to be boiling the data down into.  As agreed, the list should be limited to <= 8 per section as that will make things easier to visualise.

What I recommend is that we each take a look at the sample data (what was the URL again?) and post comments here to suggest elements of the list.  As a starting point, I'm going to suggest that we should at least have the following:
### Ministers
- Role
- Name
- Date range role was held
### People they met with (need a better name)
- Name
- Role (`lobbyist`, `advisor`, ?)
- Organisation represented
- Interest
### Meetings
- Minister Role (link to above)
- Met with (link to above)
- Meeting subject
- Tags: `fossil fuels`, `finance`, `environment`, ?
- Date
### Gifts
- Minister Role (link to above)
- Giver (link to above)
- Date
- Value?
- ?

With that little bit of info, we can draw connections between lobbyist and minister time, or interest and minister time.  We can show if more or less attention was given to `subject` before or after a new minister took the job.

The thing to do is (a) find some form of agreement on the headers (minister role, meeting subject, etc.) _and_ agreement on the tags used (`lobbyist`, `fossil fuels`, etc.) and that can only be done by having a human look at the data and come up with a good list.

Sound good?

**Comment by charlottebrf** [comment]
This looks good! Thanks so much for this speedy input @elischutze

**Comment by elischutze** [comment]
Looking good! 

Under meetings, I would possibly separate out the "meeting subject" and the "subject tags" into two fields so that the original supplied meeting purpose is visible in addition to being able to relate it to topics. 

It's worth noting that 'people they met with' can vary and is sometimes just the name of the org, or is specified as a list of orgs so they would each require an individual node (but was all the same meeting) 

We should also specify what constitutes meeting uniqueness so that they can be identified as the same meeting or different meetings. 

Other than that, I think we're good there! 

We should also remain open to tweak slightly as we uncover more data sources.

**Comment by danielquinn** [comment]
I've updated the meeting architecture to separate subject & tags.  Your other comments were all good, but as they didn't affect the structure, I had nothing to update :-)
