### ISSUE TITLE
ui: display name of entity above bubble chart

### ISSUE THREAD

**Issue by aspiers** [HackBrexit/MinistersUnderTheInfluence#142]
## Description

It's not yet clear what the bubbles relate to; there should be an entity name displayed above the bubble chart.

## Comments, Questions and Considerations

We can get the name by adding the type to the `?include=` part of the API query string, e.g. if we're viewing meetings for a given minister, then `?include=organisations,people` would return data on *all* people involved in the meetings, not just that minister.  This might be overkill; OTOH the names of the other people involved might come in handy for displaying meeting details within the tool-tips or in some other fancy drill-down UI feature.

## Acceptance Criteria

This story can be considered done when the following acceptance tests
are satisfied:

**Given** a running frontend

**When** I visit a bubble chart for a given entity (person/organisation/office)

**Then** I can see the name of that entity above the bubble chart.

**Comment by Greatlemer** [comment]
@aspiers  I think that may be overkill for now. Will we not be having a list somewhere that stores the data on who's who in terms of organisations,ministers and departments (in order to produce the homepage lists in the future). Could it be looked up from that?
Perhaps the hardcoded version could be set up to work with a mock version of the data for now so that it's available?
