### ISSUE TITLE
Python preprocesser - clean up dates in files to show missing date information in consistent structure

### ISSUE THREAD

**Issue by charlottebrf** [HackBrexit/MinistersUnderTheInfluence#38]
- Continue working on script to clean the data files. Standardising date system.(Jo)

**Comment by eddiejaoude** [comment]
Questions:
- Which script? Path/link to code in repo
- Which data files? Path/link to example data files 
- Current state of script?

**Comment by jo-osborne** [comment]
### More Info:
- This task relates to [the csv-reader script](https://github.com/HackBrexit/MinistersUnderTheInfluence/tree/master/src/python/csv-reader)
- The sample data files are described in the [csv-reader Readme](https://github.com/HackBrexit/MinistersUnderTheInfluence/blob/master/src/python/csv-reader/README.md)
- How to run the script is described in the readme. You will need python 2.7.11 installed to do so.
- Current state of the script:
  At the moment it reads the sample csv files, removes empty columns and rows, removes boilerplate and header rows and prints the output to the screen like this:

> ['Minister for Civil Society, Nick Hurd', 'Dec-11', 'NPC', 'Big Society Policy']
> ['Minister for Civil Society, Nick Hurd', 'Dec-11', 'Not all Bad', 'Big Society Policy']
> ['Minister for Civil Society, Nick Hurd', 'Dec-11', 'Middlesbrough & Teeside Philanthropic Foundation', 'Big Society Policy ']
> ['Minister for Civil Society, Nick Hurd', 'Dec-11', 'Community Foundation Network', 'Big Society Policy']
> ['Minister without Portfolio, The Rt Hon Baroness Warsi', 'Nov-11', 'JHub, Mitzvah Day, Jewish Volunteer Network, Schools Linking Network, Three Faiths Forum, Pears Foundation', 'Faith based enterprise and social action']
> ['Minister without Portfolio, The Rt Hon Baroness Warsi', 'Dec-11', 'Muslim Leadership Panel', 'Introductory Meeting']
> ['Minister without Portfolio, The Rt Hon Baroness Warsi', 'Dec-11', 'The Samosa', 'To discuss the charity\x92s work in Pakistan']
> ['Leader of the House of Commons and Lord Privy Seal, The Rt Hon Andrew Lansley MP', 'January', 'Crisis', 'Transparency Bill']
> ['Leader of the House of Commons and Lord Privy Seal, The Rt Hon Andrew Lansley MP', 'January', 'Oxfam, Big Brother Watch, Counytryside Alliance, NCVO, ACEVO', 'Transparency Bill']
> ['Leader of the House of Commons and Lord Privy Seal, The Rt Hon Andrew Lansley MP', 'March', 'IPSA', 'Bilateral']
> ['Parliamentary Secretary, Deputy Leader of the House of Commons, The Rt Hon Tom Brake MP', 'January', 'Crisis', 'Transparency Bill']
> ['Parliamentary Secretary, Deputy Leader of the House of Commons, The Rt Hon Tom Brake MP', 'January', 'Oxfam, Big Brother Watch, Counytryside Alliance, NCVO, ACEVO', 'Transparency Bill']

### This task - dates!

  Looking through the output you will notice that the date information is inconsistent and in some cases incomplete - it may just say `January` without specifying the year for example. The dates need to be formatted consistently. In cases where we are missing data, for example the year as above, it is fine to format with a placeholder for now, since this data will ultimately be provided by momo's webscraper.

So for example when this is done, the data above might look like this:

> ['Minister for Civil Society, Nick Hurd', 'XX-12-2011', 'NPC', 'Big Society Policy']
> ['Minister for Civil Society, Nick Hurd', 'XX-12-2011', 'Not all Bad', 'Big Society Policy']
> ['Minister for Civil Society, Nick Hurd', 'XX-12-2011', 'Middlesbrough & Teeside Philanthropic Foundation', 'Big Society Policy ']
> ['Minister for Civil Society, Nick Hurd', 'XX-12-2011', 'Community Foundation Network', 'Big Society Policy']
> ['Minister without Portfolio, The Rt Hon Baroness Warsi', 'XX-11-2011', 'JHub, Mitzvah Day, Jewish Volunteer Network, Schools Linking Network, Three Faiths Forum, Pears Foundation', 'Faith based enterprise and social action']
> ['Minister without Portfolio, The Rt Hon Baroness Warsi', 'XX-12-2011', 'Muslim Leadership Panel', 'Introductory Meeting']
> ['Minister without Portfolio, The Rt Hon Baroness Warsi', 'XX-12-2011', 'The Samosa', 'To discuss the charity\x92s work in Pakistan']
> ['Leader of the House of Commons and Lord Privy Seal, The Rt Hon Andrew Lansley MP', 'XX-01-XXXX', 'Crisis', 'Transparency Bill']
> ['Leader of the House of Commons and Lord Privy Seal, The Rt Hon Andrew Lansley MP', 'XX-01-XXXX', 'Oxfam, Big Brother Watch, Counytryside Alliance, NCVO, ACEVO', 'Transparency Bill']
> ['Leader of the House of Commons and Lord Privy Seal, The Rt Hon Andrew Lansley MP', 'XX-03-XXXX', 'IPSA', 'Bilateral']
> ['Parliamentary Secretary, Deputy Leader of the House of Commons, The Rt Hon Tom Brake MP', 'XX-01-XXXX', 'Crisis', 'Transparency Bill']
> ['Parliamentary Secretary, Deputy Leader of the House of Commons, The Rt Hon Tom Brake MP', 'XX-01-XXXX', 'Oxfam, Big Brother Watch, Counytryside Alliance, NCVO, ACEVO', 'Transparency Bill']

In this example I have used a date format of `dd-mm-yyyy` and have used the character `X` to denote missing information. So the date `Dec-11` becomes `XX-12-2011` and the date `January` becomes `XX-01-XXXX`.

Don't worry about all the X's for now - we shall fill them in later. This is a really nice small task for anyone looking to add some value and play with python :)

**Comment by elischutze** [comment]
@jo-osborne i've merged this (partially accidentally) but it mostly works with the caveat that it has no support for cases where the line date is in the format "Jan/Feb/March" and assumes the exact day is never supplied and the month always is. Give it a look and maybe we can close/rework this issue!

**Comment by jo-osborne** [comment]
@elischutze This looks great! Thanks for doing it, I was feeling bad for not making any progress!

I am now working on adding a proper package structure, splitting the file up into modules and adding tests. This will help us to work on these edge cases I think but this is a great start! :+1: 

If you would like to see what I am doing, it is on my fork and very much a wip - but I would appreciate any feedback from you :)

**Comment by elischutze** [comment]
This is now issues #58  and #61
